version: '3.3'
services:
  web:
    container_name: php73
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on: 
      - db
    volumes: 
      - ./html:/var/www/html/
      - ./php:/var/www/html/php/
    ports: 
      - 8000:80
  db: 
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password    
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports: 
      - 6033:3306
    

